### ISSUE TITLE
Backend development

### ISSUE THREAD

**Issue by puneeth072003** [puneeth072003/Vitista#2]
Using GoLang to build a backend server

## To-do:
- [x] Backend init 
- [x] Login and Sigin In
- [x] Implementation of scheduling feature in backend
- [x] Implementation of ML model analysis logic in backend
- [x] Fitness tracking feature.
- [x] Health consoultancy logic.
- [x] Diet planner and weight managing logic.
- [x] Journals and tipping service.
